This is work getting the conferencing service wrapped in Python so that it can be tested. There are also a number of tweaks to the test script to make it a bit more functional.

diff --git a/test.sh.in b/test.sh.in
--- a/test.sh.in
+++ b/test.sh.in
@@ -1,63 +1,92 @@
 #! /bin/sh
 
+
 # Test script for Python wrappers
 #
 # If you don't have a test.conf, copy it from test.conf.in and modify
 # as necessary.
 
+
 # values determined from options passed to ./configure
-PYDOC=@PYDOC@
 PYTHON=@PYTHON@
 PYLIBDIR=@PYTHON_LIBP@
 
+CONFIG=test.conf
+
+
 # if not configured with python support, than this script can't run
 if test "$PYTHON" = "" ; then
-	echo "error: python support not built"
-	exit 1
+    echo "error: python support not built"
+    exit 1
 fi
+
 
 # obtain configuration data
-if [ -f 'test.conf' ] ; then
-	. test.conf
-else
-	echo "error: please create test.conf as described in test.conf.in"
-	exit 1
+if test ! -e $CONFIG ; then
+    cp $CONFIG.in $CONFIG
+    if test -n `which vim` ; then
+	vim $CONFIG
+    fi
 fi
 
-# help
+. $CONFIG
+
+if test -z "$mw_user" || test -z "$mw_host" ; then
+    echo "Please modify $CONFIG to provide the correct server" \
+	"and user information."
+    exit 1
+fi
+
+
+# help message
 if test "$1" = "help" ; then
 	echo "\
 Meanwhile Python Test Script -
+
   Execute to log in to server using test ID from test.conf and act as a
 simple bot. See src/python/test.py for test script. This does not require
 the meanwhile library or the python wrappers to be actually installed, just
 compiled.
 
  Options:
-    test.sh help        this message
-    test.sh debug       run the python interpreter and script from gdb
-    test.sh pydoc [m]   get pydoc information for m
+    test.sh help      prints this helpful message
+    test.sh           run the python interpreter and test bot
+    test.sh debug     run the python interpreter and test bot from gdb
+    test.sh pydoc     get pydoc information for m
+    test.sh valgrind  run the python interpreter and test bot in valgrind
 "
 	exit 0
 fi
 
 
+# we don't require the module to be installed for the script to run
+# but that means we'll need to put ourselves into a position to find
+# the library and module
 cd src/python
 export LD_LIBRARY_PATH=$PYLIBDIR/../:../.libs/
 
 
+# debug
 if test "$1" = "debug" ; then
-	echo run | gdb --quiet --args $PYTHON -v test.py
+    echo run | gdb --quiet --args $PYTHON -v test.py
 
+# valgrind
 elif test "$1" = "valgrind" ; then
-	shift
+    shift
+    if test -n `which valgrind` ; then
 	valgrind $* $PYTHON test.py
+    else
+	echo "valgrind not found in \$PATH"
+	exit 1
+    fi
 
+# pydoc
 elif test "$1" = "pydoc" ; then
-	shift
-	$PYDOC $*
+    shift
+    $PYTHON -c "import pydoc; pydoc.cli();" $*
 
+# test bot
 else
-	$PYTHON test.py 
+    $PYTHON test.py 
 fi
 
